const ACTION_TYPES = {
  GET_SURVEYS_SUCCESS: 'GET_SURVEYS_SUCCESS',
  ADD_NEW_SURVEY_SUCCESS: 'ADD_NEW_SURVEY_SUCCESS',
  GET_SURVEY_BY_ID_SUCCESS: 'GET_SURVEY_BY_ID_SUCCESS',
  GET_RESULTS_SUCCESS: 'GET_RESULTS_SUCCESS',
};

export default ACTION_TYPES;
